title = "Gluten-Free Favorites"
# logo = "URL to logo" TODO
base_url = "http://localhost:3000"
about = "TODO"
index_site_pages = ["regions", "favorites", "region"]
# Enable gzip content encoding for all HTML. This speeds up transfer.
content_encoding = "gzip"

[extra]
copyright = "Caleb Schoepp"
keywords = "glutenfree, gluten-free, gf, travel"

date_style = "%B %e, %Y"
